server:
  servlet:
    context-path: /meett

spring:

  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    database: mysql

    hibernate:
      ddl-auto: create

      order_insert: true
      order_update: true
      jdbc:
        batch_size: 100


    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/MeettDB"
    username: "root"
    password: "!Biz12341234"

logging:
  level:
    root: info
    com.team.meett: debug